name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Release Branch
        run: git checkout -b release-${{ github.sha }}
      - name: Build
        uses: ./.github/actions/build
      - name: Release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{secrets.GIT_AUTHOR_NAME}}
          GIT_AUTHOR_EMAIL: ${{secrets.GIT_AUTHOR_EMAIL}}
          GIT_COMMITTER_NAME: ${{secrets.GIT_COMMITTER_NAME}}
          GIT_COMMITTER_EMAIL: ${{secrets.GIT_COMMITTER_EMAIL}}
        run: npx semantic-release
      - name: Merge Release Branch
        if: always()
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff release-${{ github.sha }} -m "Merge release branch '${{ github.sha }}'"
          git push origin main