name: Test

on: push

jobs:
  canCreateRuleFile:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./.github/actions/build
      - run: yarn createRule

  testLint:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./.github/actions/build
      - run: yarn testLint


  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./.github/actions/build
      - run: yarn test
