name: Test

on:
  push:
    branches:
      - "!main"

jobs:
  canCreateRuleFile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
      - run: yarn createRule

  testLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
      - run: yarn testLint

  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
      - run: yarn test
