on:
  schedule:
    - cron:  '0 9 * * *'
env:
  BASE_BRANCH: main
  REVIEWER: bun913
name: CI
jobs:
  createPRIfNeeded:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/build
      - name: createRuleFile
        run: yarn createRule
      # 差分のチェック
      - uses: technote-space/get-diff-action@v6
        id: check-diff
        with:
          FILES: |
            dict/auto-create-regulaer-rules.yml
      # 差分があればPR作成
      - name: Create PR
        run: gh pr create --fill -B ${{ env.BASE_BRANCH }} -r ${{ env.REVIEWER }}
        if: env.GIT_DIFF
